#Write a program to create a Mini Calculator
a=float(input("Enter First Number = "))   
b=float(input("Enter Second Number : "))       
print("Sum of 2 Nos. : ",a," + ",b," = ",(a+b)) 
print("Subtract of 2 Nos. : ",a, " - ", b, " = " ,(a-b))
print("Multiply of 2 Nos. : ",(a*b))
print("Divide of 2 Nos. = ",(a/b))
print("Integer division of 2 Nos. : ",(a//b))
print("Remainder of 2 Nos. : ",(a%b))
print("Power of given base  : ",(a**b))
